### ISSUE TITLE
Invalid llvm.zext operation generated by btor2mlir-opt

### ISSUE THREAD

**Issue by Po-Chun-Chien** [jetafese/btor2mlir#27]
(follow up https://github.com/agurfinkel/btor2mlir/issues/37)

I ran the below steps (using the commands from [`get_cex_seahorn.sh`](https://github.com/jetafese/btor2mlir/blob/345625097142e221be4c3a7241d99df9599cc955/utils/cex/witness/get_cex_seahorn.sh#L34-L40))
to translate the Btor2 circuit [recount4.btor2](https://github.com/Boolector/btor2tools/blob/8775f9ad9caed51d3daa30a416b1a94dfec532b0/examples/btorsim/recount4.btor2) to an LLVM-IR program.
A docker image built from commit 3456250 was used.

1. `btor2mlir-translate --import-btor recount4.btor2 >recount4.mlir`
2. `btor2mlir-opt --convert-btornd-to-llvm --convert-btor-to-vector --convert-arith-to-llvm --convert-std-to-llvm --convert-btor-to-llvm --convert-vector-to-llvm recount4.mlir >recount4.mlir.opt`
3. `btor2mlir-translate --mlir-to-llvmir recount4.mlir.opt >recount4.ll`

The first 2 steps succeeded, but the 3rd one failed with the error message:

```
Type too small for ZExt
  %6 = zext i32 %4 to i1, !dbg !13
Type too small for ZExt
  %10 = zext i32 %8 to i1, !dbg !18
```

I further inspected the generated `recount4.mlir.opt`, it contains the following lines:

```bash
$ grep -i zext recount4.mlir.opt 
    %6 = llvm.zext %5 : i1 to i64
    %8 = llvm.zext %4 : i32 to i64
    %9 = llvm.zext %4 : i32 to i1
    %14 = llvm.zext %13 : i1 to i64
    %16 = llvm.zext %12 : i32 to i64
    %17 = llvm.zext %12 : i32 to i
```

There seems to be some invalid `zext` operations in that file.

**Comment by jetafese** [comment]
Fixed by commit: 2e06dec
